#!/bin/bash
RTMP_URL=$1
STREAM_KEY=$2

if [[ -z $RTMP_URL || -z $STREAM_KEY ]]; then
   echo "usage: ustream RTMP-URL STREAM-KEY"
   exit 1
fi 

raspivid -n -vf -hf -t 0 -w 960 -h 540 -fps 25 -b 500000 -o - 2> /dev/null | ffmpeg -i - -vcodec copy -an -metadata title="HenHouse Cam" -f flv $RTMP_URL/$STREAM_KEY 2> /dev/null
